// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  inPosition: string;
  inWord: string;
  letter: string;
  notInWord: string;
  unused: string;
}
export const cssExports: CssExports;
export default cssExports;
